### ISSUE TITLE
Need to specify asset path for functions to work

### ISSUE THREAD

**Issue by drdogbot7** [bpolaszek/webpack-encore-resolver#1]
I had to specify my asset path in the functions in order for them to resolve properly. Based on the examples in the README I had assumed it would parse my `webpack.config.js`.

Unless you specify a directory, it assumes your `manifest.json` and `entrypoints.json` are in a folder called `build` in the root of your public directory.

This will throw an error if your path is different:
```php
<?php
use function BenTools\WebpackEncoreResolver\asset;
?>
<link rel="stylesheet" href="<?=asset('main.css')?>">
```
But this will work:
```php
<?php
use function BenTools\WebpackEncoreResolver\asset;
?>
<link rel="stylesheet" href="<?=asset('main.css', 'PATH_TO_PUBLIC_DIR/dist/')?>">
```

This is probably not even a bug per se, just not fully documented.

**Comment by bpolaszek** [comment]
Hey @drdogbot7 ,

Thanks for your interest.
Indeed, when you're using different build path than the default one, you have to specify the path as a second argument.

You can also set it globally:
```php
use BenTools\WebpackEncoreResolver\AssetPathResolver;

AssetPathResolver::setDefaultDirectory('PATH_TO_PUBLIC_DIR/dist/');
```

I'll update the README to reflect this.

Thank you,
Ben
